import type { Metadata } from "next";
import { ArrowLeft } from "lucide-react";
import { DraftHelper } from "@/components/draft/DraftHelper";
import type { DraftBoard } from "@/lib/draft/board-types";
import { CATEGORY_SHORT, formatDateFr, formatDraftStartFr } from "@/lib/draft/draft-copy";
import { SITE_BRAND, homeRankingsHref } from "@/lib/site";
// Generated by `npm run draft:board` (committed, and rebuilt by
// `build:pages` before `next build`, so a deploy always matches players.json).
// Read at build time — the static page ships with the board inlined, so it
// keeps working if the network drops mid-draft.
import boardJson from "../../../../public/leagues/light-the-lamp/board.json";

const board = boardJson as unknown as DraftBoard;

const PATH = "/draft/light-the-lamp";
const TITLE = `${board.leagueName} — assistant de repêchage`;
const CATEGORIES = [...board.categories.skater, ...board.categories.goalie]
  .map((c) => CATEGORY_SHORT[c])
  .join(", ");
const DESCRIPTION = `Assistant de repêchage en direct pour la ligue Yahoo ${board.leagueName} (${board.league.teams} équipes, têtes-à-têtes par catégories : ${CATEGORIES}) : classement VOR, suggestions et suivi de mon équipe.`;

// Private-league tool: public data only, but not meant for search results.
export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  robots: {
    index: false,
    follow: false,
    googleBot: { index: false, follow: false },
  },
  alternates: { canonical: PATH },
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    url: PATH,
    siteName: SITE_BRAND,
    type: "website",
    locale: "fr_CA",
  },
  twitter: { card: "summary", title: TITLE, description: DESCRIPTION },
};

export default function LightTheLampDraftPage() {
  const rounds = board.league.rounds;
  return (
    <main
      lang="fr-CA"
      className="min-h-screen pb-[max(5rem,calc(env(safe-area-inset-bottom,0px)+4rem))]"
    >
      {/* The shared root layout says lang="en"; this page (title and meta
          included) is French. Switch before first paint so screen readers
          and translation prompts see fr-CA (the root <html> carries
          suppressHydrationWarning for this one attribute); DraftHelper
          restores "en" if the user navigates away client-side. */}
      <script dangerouslySetInnerHTML={{ __html: 'document.documentElement.lang="fr-CA"' }} />
      <header className="mx-auto max-w-[96rem] px-4 pb-3 pt-[max(1.25rem,env(safe-area-inset-top,0px))] sm:px-6 lg:px-8">
        <div className="flex flex-wrap items-center justify-between gap-2">
          <p className="text-xs font-medium uppercase tracking-[0.2em] text-cyan-400">
            {SITE_BRAND} · Repêchage
          </p>
          <a
            href={homeRankingsHref()}
            className="inline-flex min-h-9 items-center gap-1 rounded-lg px-2 text-xs text-slate-400 hover:bg-white/5 hover:text-white"
          >
            <ArrowLeft className="h-3.5 w-3.5" aria-hidden="true" />
            Classement principal
          </a>
        </div>
        <h1 className="mt-1 text-xl font-bold tracking-tight text-white sm:text-3xl">
          {board.leagueName}{" "}
          <span className="text-slate-400">— assistant de repêchage</span>
        </h1>
        <p className="mt-1 text-xs text-slate-400 sm:text-sm">
          Yahoo · {board.league.teams} équipes · têtes-à-têtes par catégories ({CATEGORIES}) ·
          repêchage serpent de {rounds} rondes le{" "}
          <time dateTime={board.league.draftStartsAt} className="text-slate-200">
            {formatDraftStartFr(board.league.draftStartsAt)}
          </time>{" "}
          · {board.league.pickSeconds} s par choix
        </p>
        <p className="mt-1 hidden text-xs text-slate-500 sm:block">
          Projections du {formatDateFr(board.source.projectionsGeneratedAt)} · ADP Fantrax du{" "}
          {formatDateFr(board.source.adpFetchedAt)} (proxy) · aucune donnée privée de la ligue
        </p>
      </header>
      <DraftHelper board={board} />
    </main>
  );
}
