import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { CategoryDraftTab } from "@/components/draft/CategoryDraftTab";
import { SnakeDisclaimerShort } from "@/components/snake/SnakeDisclaimer";
import summaryJson from "@/data/snake-summary.json";
import type { DraftBoard } from "@/lib/draft/board-types";
import { CATEGORY_SHORT, formatDateFr, formatDraftStartFr } from "@/lib/draft/draft-copy";
import { leagueTabPath } from "@/lib/leagues/routes";
import { SITE_BRAND } from "@/lib/site";
import { snakeNhlSeed } from "@/lib/snake/league-seed";
import type { SnakeSummaryFile } from "@/lib/snake/types";
// Generated by `npm run draft:board` (committed, and rebuilt by
// `build:pages` before `next build`, so a deploy always matches players.json).
// Read at build time — the static page ships with the board inlined, so it
// keeps working if the network drops mid-draft.
import boardJson from "../../../../public/leagues/light-the-lamp/board.json";

const board = boardJson as unknown as DraftBoard;
// Snake's verdicts for the board's players he discussed: the chips need no fetch mid-draft.
const seed = snakeNhlSeed(
  board.players.map((p) => p.id),
  summaryJson as unknown as SnakeSummaryFile,
);

// The old address of the draft helper, kept as a real page (same helper,
// same browser storage) until after the draft; then a redirect stub.
const PATH = "/draft/light-the-lamp";
const NEW_PATH = leagueTabPath("light-the-lamp", "repechage");
const TITLE = `${board.leagueName} — assistant de repêchage`;
const CATEGORIES = [...board.categories.skater, ...board.categories.goalie]
  .map((c) => CATEGORY_SHORT[c])
  .join(", ");
const DESCRIPTION = `Assistant de repêchage en direct pour la ligue Yahoo ${board.leagueName} (${board.league.teams} équipes, têtes-à-têtes par catégories : ${CATEGORIES}) : valeurs VOR, suggestions et suivi de mon équipe.`;

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  alternates: { canonical: PATH },
  openGraph: {
    title: `${TITLE} | ${SITE_BRAND}`,
    description: DESCRIPTION,
    url: PATH,
    siteName: SITE_BRAND,
    type: "website",
    locale: "fr_CA",
  },
  twitter: { card: "summary", title: `${TITLE} | ${SITE_BRAND}`, description: DESCRIPTION },
};

export default function LightTheLampDraftPage() {
  const rounds = board.league.rounds;
  return (
    <div className="pb-[max(5rem,calc(env(safe-area-inset-bottom,0px)+4rem))]">
      <header className="mx-auto max-w-[96rem] px-4 pb-3 pt-4 sm:px-6 lg:px-8">
        <p className="mb-3 flex flex-wrap items-center gap-x-2 gap-y-1 rounded-xl border border-cyan-400/40 bg-cyan-500/10 px-3 py-2 text-sm text-cyan-50">
          <span>Nouvelle adresse :</span>
          <Link
            href={NEW_PATH}
            prefetch={false}
            className="inline-flex min-h-11 items-center gap-1 rounded-md font-semibold text-cyan-200 underline underline-offset-2 hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-400"
          >
            Light the Lamp › Repêchage
            <ArrowRight className="h-4 w-4" aria-hidden="true" />
          </Link>
          <span className="text-cyan-100/80">(mettez votre favori à jour : vos choix marqués y sont déjà)</span>
        </p>
        <p className="text-xs font-medium uppercase tracking-[0.2em] text-cyan-400">Repêchage</p>
        <h1 className="mt-1 text-xl font-bold tracking-tight text-white sm:text-3xl">
          {board.leagueName} <span className="text-slate-400">— assistant de repêchage</span>
        </h1>
        <p className="mt-1 text-xs text-slate-400 sm:text-sm">
          Yahoo · {board.league.teams} équipes · têtes-à-têtes par catégories ({CATEGORIES}) · repêchage serpent de{" "}
          {rounds} rondes le{" "}
          <time dateTime={board.league.draftStartsAt} className="text-slate-200">
            {formatDraftStartFr(board.league.draftStartsAt)}
          </time>{" "}
          · {board.league.pickSeconds} s par choix
        </p>
        <p className="mt-1 hidden text-xs text-slate-400 sm:block">
          Projections du {formatDateFr(board.source.projectionsGeneratedAt)} · ADP Fantrax du{" "}
          {formatDateFr(board.source.adpFetchedAt)} (proxy) · aucune donnée privée de la ligue
        </p>
        {/* The board's rows carry Snake's chips (their legend is under the board). */}
        <SnakeDisclaimerShort className="mt-2 max-w-3xl" />
      </header>
      <CategoryDraftTab board={board} seed={seed} />
    </div>
  );
}
