/**
 * Lightweight UI contract checks (no browser). Fails if critical board hooks vanish.
 * Run: npx tsx scripts/check-ui-contracts.ts
 */
import { readFileSync } from "fs";
import { join } from "path";

const root = process.cwd();
const files: Record<string, string[]> = {
  "src/components/RankingsTable.tsx": [
    "RankingsTableInner",
    "Suspense",
    "loadingRankingsCopy",
    'role="status"',
  ],
  "src/components/RankingsTableInner.tsx": [
    'id="rankings"',
    "usePlayerDetails",
    "useRankingsBoardState",
    "useRankingsUrlSync",
    "useRankingsKeyboard",
    "useBoardCopyLinks",
    "useRankingsHashJump",
    "RankingsBoardTable",
    "BoardShortcutsHelp",
    "RankingsBoardChrome",
    "RankingsStatusBar",
    "useHorizontalScrollShadow",
    "useBoardDocumentTitle",
    "useExpandedRowScroll",
    "visibleBoardPlayers",
    "onCyclePosition",
    "cycleBoardPosition",
    "onCopyPlayerLink",
  ],
  "src/lib/board-visible.ts": ["visibleBoardPlayers", "boardRowTabStopId"],
  "src/hooks/useExpandedRowScroll.ts": [
    "useExpandedRowScroll",
    "scrollExpandedRowIntoView",
    "Intentionally ignores load-more",
  ],
  "src/components/RankingsBoardTable.tsx": [
    'id="rankings-board-table"',
    "RankingsPlayerRow",
    "RankingsTableHead",
    "RankingsBoardFooter",
    "group/hscroll",
    "overscroll-x-contain",
    "boardRowTabStopId",
    "anchorId",
  ],
  "src/hooks/useBoardCopyLinks.ts": [
    "useBoardCopyLinks",
    "copyTextWithFlash",
    "rankingsShareUrl",
    "copyBoardLink",
    "copyPlayerLink",
    "boardShareState(null)",
    "cancelBoardFlashRef",
    "cancelPlayerFlashRef",
  ],
  "src/hooks/useRankingsHashJump.ts": [
    "useRankingsHashJump",
    "hashchange",
    "scrollToRankings",
    "rankingsHashShouldFocusSearch",
    "focusSearch",
  ],
  "src/hooks/useTimedFlash.ts": [
    "useTimedFlash",
    "clearTimeout",
    "holdMs",
  ],
  "src/hooks/useBoardDocumentTitle.ts": [
    "useBoardDocumentTitle",
    "boardDocumentTitle",
    "document.title",
    "siteDefaultTitle",
    "return () =>",
  ],
  "src/lib/board-document-title.ts": [
    "boardDocumentTitle",
    "SITE_BRAND",
    "siteDefaultTitle",
  ],
  "src/hooks/useRankingsBoardState.ts": [
    "useRankingsBoardState",
    "boardFilterResetToken",
    "coerceExpandedPlayerId",
    "countActiveStatFilters",
    "resetSortToVor",
    "toggleDepthGoalies",
    "hydrateFromUrl",
    "Drop expand when the player leaves",
    "pruneStatRangesForPosition",
    "canToggleDepthGoalies",
  ],
  "src/components/RankingsBoardChrome.tsx": [
    "boardFiltersRegionLabel",
    "motion-reduce:backdrop-blur-none",
    "motion-reduce:bg-slate-950",
    "data-board-sticky-chrome",
    "BoardActiveFilters",
    "RankingsToolbar",
  ],
  "src/components/RankingsBoardFooter.tsx": [
    "loadMoreLabel",
    "loadMoreAriaLabel",
    "remainingBoardRows",
    "RankingsEmptyState",
    'aria-keyshortcuts="m"',
  ],
  "src/lib/board-players.ts": ["boardHasPlayerId", "coerceExpandedPlayerId"],
  "src/lib/board-active-filters.ts": ["countActiveStatFilters"],
  "src/components/RankingsPlayerRow.tsx": [
    "aria-expanded",
    "aria-controls",
    "isExpanded ? `player-panel-${player.id}` : undefined",
    "isTabStop",
    'role="region"',
    "aria-busy",
    "vorForFilter",
    "ExpandedPlayerPanel",
    "isBoardRowToggleKey",
    "boardRowAriaLabel",
    "boardRowDetailsAriaLabel",
    "edgeCellTitle",
    "sigmaCellTitle",
    "sigmaCellDisplay",
    "tabular-nums",
  ],
  "src/lib/board-row-a11y.ts": [
    "boardRowAriaLabel",
    "boardRowDetailsAriaLabel",
    "edgeCellTitle",
    "sigmaCellTitle",
    "sigmaCellDisplay",
  ],
  "src/lib/board-reset-token.ts": [
    "boardFilterResetToken",
    "encodeActiveStatRangesToken",
    "g1",
  ],
  "src/lib/board-keyboard.ts": [
    "nextExpandedPlayerId",
    "isBoardRowToggleKey",
    "isBoardTypingTarget",
    "isBoardChromeTarget",
    "shouldIgnoreBoardShortcut",
    "boardKeyboardNavIds",
    "nextBoardEscapeTypingAction",
    "isBoardImeComposing",
  ],
  "src/components/BoardActiveFilters.tsx": [
    "Active board filters",
    "clearBoardFiltersCopy",
    "boardActiveStatChips",
    "boardActiveFiltersVisible",
    "hasStatFilters",
    "All goalies",
    "showingAllGoalies",
  ],
  "src/lib/board-active-filter-chips.ts": [
    "boardActiveStatChips",
    "boardActiveFiltersVisible",
    "formatActiveRangeChip",
    "formatRangeChip",
  ],
  "src/components/RankingsTableHead.tsx": [
    'column="sigma"',
    "sticky left-10",
    "STICKY_NAME_SHADOW",
    "onResetSort",
    'scope="col"',
    "motion-reduce:bg-slate-950",
  ],
  "src/components/RankingsEmptyState.tsx": [
    "emptyBoardStatusCopy",
    "emptyBoardHintCopy",
    "EMPTY_BOARD_ACTION_LABELS",
    "EmptyAction",
    'role="status"',
    'keyshortcuts="Escape"',
    "emptyBoardRecoveryFlags",
  ],
  "src/components/EmptyAction.tsx": [
    "EmptyAction",
    "aria-keyshortcuts",
    "primary",
  ],
  "src/lib/board-empty-recovery.ts": [
    "emptyBoardRecoveryFlags",
    "emptyBoardStatusCopy",
    "emptyBoardHintCopy",
    "EMPTY_BOARD_ACTION_LABELS",
    "clearBoardFiltersCopy",
    "canShowAllGoalies",
  ],
  "src/components/RankingsStatusBar.tsx": [
    "aria-live",
    "boardShowingSummary",
    "Enter/Space",
    "boardShortcutsStatusCopy",
    "tabular-nums",
  ],
  "src/lib/board-status.ts": ["boardShowingSummary", "formatCount"],
  "src/hooks/useRankingsKeyboard.ts": [
    'e.key === "/"',
    "!helpOpenNow",
    "ArrowDown",
    "BOARD_SORT_HOTKEYS",
    "onResetBoard",
    "filteredRef",
    "renderCountRef",
    "focusStatsFilterButton",
    "focusFirstStatFilterInput",
    "onCopyBoardLink",
    "onCopyPlayerLink",
    'e.key === "Home"',
    'e.key === "End"',
    "nextExpandedPlayerId",
    "boardKeyboardNavIds",
    "nextBoardEscapeTypingAction",
    "shouldIgnoreBoardShortcut",
    "isBoardTypingTarget",
    "focusPlayerRowIfPanelFocused",
    "onToggleDepthGoalies",
    "onLoadMore",
    "onClearSearch",
    "onCyclePosition",
    'e.key === "G"',
    'e.key === "m"',
    'e.key === "p"',
    'e.key === "["',
  ],
  "src/components/BoardShortcutsHelp.tsx": [
    "Board shortcuts",
    "BOARD_SHORTCUT_ROWS",
    "board-shortcuts-dialog",
    "useDialogFocusTrap",
  ],
  "src/hooks/useDialogFocusTrap.ts": [
    "useDialogFocusTrap",
    "trapDialogTabKey",
    "dialogFocusableElements",
    "useLayoutEffect",
    "previouslyFocused",
    "isConnected",
    "Escape",
  ],
  "src/lib/dialog-focus.ts": [
    "dialogFocusableElements",
    "trapDialogTabKey",
    "pull it back",
  ],
  "src/lib/board-shortcuts.ts": [
    "BOARD_SHORTCUT_ROWS",
    "BOARD_SORT_HOTKEYS",
    "boardShortcutsStatusCopy",
    "boardShortcutsFooterChip",
    "boardShortcutsFaqAnswer",
    "Shift+G",
    "Load more rows",
    "Copy expanded player link",
    "Previous / next position tab",
  ],
  "src/lib/copy-flash.ts": [
    "copyTextWithFlash",
    "CopyFlash",
    "boardLinkButtonLabel",
    "boardLinkTitle",
    "playerLinkButtonLabel",
    "playerLinkAriaLabel",
    "playerLinkTitle",
  ],
  "src/lib/board-dom.ts": [
    "focusStatsFilterButton",
    "focusFirstStatFilterInput",
    "focusBoardSearch",
    "rankings-stat-filters",
    "STICKY_NAME_SHADOW",
    "STICKY_NAME_BASE",
    "scrollPageTop",
    "scrollToRankings",
    "scrollExpandedRowIntoView",
    "stickyAwareScrollDelta",
    "boardStickyTopInset",
    "BOARD_STICKY_CHROME_SELECTOR",
    "data-board-sticky-chrome",
    "focusPlayerRow",
    "focusPlayerRowIfPanelFocused",
    "prefersReducedMotion",
  ],
  "src/lib/rankings-export.ts": [
    "rankingsToJsonRows",
    "rankingsJsonExport",
    "rankingsCsvString",
    "downloadRankingsCsv",
    "downloadRankingsJson",
    "exportButtonLabel",
    "exportButtonTitle",
    "exportGroupAriaLabel",
    "vorForFilter",
    "vorScope",
  ],
  "src/lib/rankings-csv.ts": [
    "rankingsToCsv",
    "downloadTextFile",
    "fantasy-hockey-vor",
    "vorScope",
    "csvEscape",
    "revokeObjectURL",
    "\\uFEFF",
  ],
  "src/components/ExpandedPlayerPanel.tsx": [
    "ExpandedPlayerMeta",
    "ExpandedPlayerCategories",
    "ExpandedPlayerNotes",
  ],
  "src/components/ExpandedPlayerNotes.tsx": [
    "playerNotesLoadingLabel",
    "playerNotesUnavailableCopy",
    "playerNotesRetryLabel",
    "sr-only",
    "resetPlayerDetailsCache",
    'role="alert"',
    'aria-busy="true"',
  ],
  "src/lib/player-notes-copy.ts": [
    "playerNotesLoadingLabel",
    "playerNotesUnavailableCopy",
    "playerNotesRetryLabel",
  ],
  "src/components/ExpandedPlayerCategories.tsx": [
    "categoryZBarWidth",
    "categoryZScoreLabel",
    "categoryZMeterAriaLabel",
    "categoryProjectionPrefix",
    "detailStatSigma",
    'role="meter"',
    "aria-valuetext",
    "tabular-nums",
  ],
  "src/lib/category-z-bar.ts": [
    "categoryZBarWidth",
    "categorySigmaDigits",
    "categoryZMeterValue",
    "categoryZScoreLabel",
    "categoryZMeterAriaLabel",
    "categoryProjectionPrefix",
  ],
  "src/components/ExpandedPlayerMeta.tsx": [
    "playerLinkButtonLabel",
    "playerLinkAriaLabel",
    "playerLinkTitle",
    'aria-keyshortcuts="p"',
    'aria-live="polite"',
    "projectionMethodLabel",
  ],
  "src/lib/expanded-meta-copy.ts": [
    "confidenceChipCopy",
    "marketEdgeChipCopy",
    "uncertaintyChipCopy",
    "uncertaintyChipTitle",
  ],
  "src/lib/projection-method.ts": [
    "projectionMethodLabel",
    "projectionMethodTone",
  ],
  "src/components/RankingsToolbar.tsx": [
    "RankingsExportButtons",
    "RankingsSearchField",
    "RankingsGoalieDepthToggle",
    "RankingsBoardLinkButton",
    "RankingsHelpButton",
    "RankingsStatsFilterButton",
    "PositionFilterTabs",
  ],
  "src/components/RankingsStatsFilterButton.tsx": [
    'aria-controls="rankings-stat-filters"',
    'aria-keyshortcuts="f"',
    "activeFilterCount",
    "statsFilterButtonLabel",
  ],
  "src/components/RankingsBoardLinkButton.tsx": [
    "boardLinkButtonLabel",
    "boardLinkTitle",
    'aria-keyshortcuts="l"',
    'aria-live="polite"',
    "onCopyBoardLink",
  ],
  "src/components/RankingsHelpButton.tsx": [
    "boardHelpTitle",
    "boardHelpAriaLabel",
    'aria-keyshortcuts="Shift+Slash"',
    "onOpenHelp",
  ],
  "src/lib/board-help-copy.ts": [
    "boardHelpTitle",
    "boardHelpAriaLabel",
  ],
  "src/lib/goalie-depth-toggle.ts": [
    "canToggleDepthGoalies",
    "canOfferAllGoalies",
    "goalieDepthToggleLabel",
    "goalieDepthToggleTitle",
  ],
  "src/components/RankingsGoalieDepthToggle.tsx": [
    "goalieDepthToggleLabel",
    "goalieDepthToggleTitle",
    'aria-keyshortcuts="Shift+G"',
    "GOALIE_DEPTH_MAX_GP",
    "aria-pressed",
  ],
  "src/components/RankingsSearchField.tsx": [
    "searchQueryNearCap",
    "searchQueryLengthLabel",
    "searchFieldAriaLabel",
    "searchFieldPlaceholder",
    "clearSearchAriaLabel",
    "HIGHLIGHT_QUERY_MAX",
    "rankings-search-limit",
    "autoComplete",
    'aria-keyshortcuts="Slash"',
    "focusBoardSearch",
  ],
  "src/lib/highlight-match.tsx": [
    "HIGHLIGHT_QUERY_MAX",
    "SEARCH_NEAR_CAP_REMAINING",
    "searchQueryNearCap",
    "searchQueryLengthLabel",
    "searchFieldAriaLabel",
    "searchFieldPlaceholder",
    "clearSearchAriaLabel",
    "highlightMatch",
  ],
  "src/components/RankingsExportButtons.tsx": [
    "exportButtonLabel",
    "exportButtonTitle",
    "exportGroupAriaLabel",
    "useTimedFlash",
    "downloadRankingsCsv",
    "downloadRankingsJson",
  ],
  "src/hooks/useBoardInfiniteScroll.ts": [
    "useBoardInfiniteScroll",
    "BOARD_PAGE_SIZE",
    "IntersectionObserver",
    "loadMore",
    "nextVisibleCount",
    "expandVisibleFloor",
    "resolveVisibleCount",
    "applyLoadMoreVisibleCount",
    "skipIoRef",
    "resetGenRef",
    "tokenMountedRef",
    "requestAnimationFrame",
    "collapsing a deep row does not yank",
  ],
  "src/hooks/useHorizontalScrollShadow.ts": [
    "useHorizontalScrollShadow",
    "applyHorizontalScrollShadow",
    "requestAnimationFrame",
    "cancelAnimationFrame",
  ],
  "src/lib/horizontal-scroll-shadow.ts": [
    "HORIZONTAL_SCROLL_SHADOW_PX",
    "HORIZONTAL_SCROLL_SCROLLED_ATTR",
    "horizontalScrollShadowVisible",
    "applyHorizontalScrollShadow",
  ],
  "src/hooks/useRankingsUrlSync.ts": [
    "history.replaceState",
    "rankingsUrlSyncHref",
    "rankingsUrlSearch",
    "nextRankingsUrlSyncAction",
    "onHydrate",
    "query,",
  ],
  "src/hooks/usePlayerDetails.ts": [
    "scheduleIdle",
    "fetchPlayerDetails",
    "expandedId == null || details != null",
    "Stay silent on idle failure",
  ],
  "src/lib/schedule-idle.ts": [
    "scheduleIdle",
    "requestIdleCallback",
    "cancelIdleCallback",
  ],
  "src/components/PositionFilterTabs.tsx": [
    'role="tablist"',
    "ArrowRight",
    "positionFilterTablistLabel",
    "BOARD_POSITIONS",
    "nextBoardPositionIndex",
    "aria-controls",
    "rankings-board-table",
    'aria-keyshortcuts="[ ]"',
    "aria-live",
    "positionFilterAnnounce",
    "boardPositionTabId",
  ],
  "src/lib/board-positions.ts": [
    "BOARD_POSITIONS",
    "nextBoardPositionIndex",
    "cycleBoardPosition",
    "boardPositionTabId",
    "positionFilterAnnounce",
    "positionFilterTablistLabel",
  ],
  "src/lib/rankings-url.ts": [
    "hideDepthGoalies",
    "playerId",
    "encodeStatRanges",
    "rf",
    "steadiestBoardHref",
    "playerBoardHref",
    "rf=${rf}",
    "HIGHLIGHT_QUERY_MAX",
    "RANGE_BOUND_MAX",
    "nextRankingsUrlSyncAction",
    "rankingsHashShouldFocusSearch",
    "rankingsUrlSyncHref",
    "pruneStatRangesForPosition",
  ],
  "src/components/ScrollToTop.tsx": [
    "scrollToTopAriaLabel",
    "scrollToTopTitle",
    "requestAnimationFrame",
    "scrollPageTop",
    "scrollToTopVisible",
    "motion-reduce:transition-none",
    "motion-reduce:backdrop-blur-none",
    'aria-keyshortcuts="Home"',
  ],
  "src/lib/scroll-to-top.ts": [
    "scrollToTopVisible",
    "scrollToTopAriaLabel",
    "scrollToTopTitle",
    "SCROLL_TOP_SHOW_AFTER",
    "SCROLL_TOP_HIDE_BELOW",
  ],
  "src/components/TopPlayerLink.tsx": [
    "TopPlayerLink",
    "dense",
    "hover:bg-white/[0.07]",
    "motion-reduce:transition-none",
  ],
  "src/app/not-found.tsx": [
    "notFoundTitle",
    "notFoundBody",
    "errorBackToRankingsCopy",
    "homeRankingsHref",
    "BrandEyebrow",
  ],
  "src/lib/seo-jsonld.ts": [
    "WebApplication",
    "Dataset",
    "FAQPage",
    "BreadcrumbList",
    "HowTo",
    "isAccessibleForFree",
    "keywords",
    "National Hockey League",
    "sameAs",
    "boardShortcutsFaqAnswer",
    "SITE_BRAND",
  ],
  "src/lib/site.ts": [
    "SITE_ORIGIN",
    "SITE_URL",
    "SITE_BRAND",
    "SITE_SHORT_NAME",
    "homeRankingsHref",
    "playerDetailsHref",
    "NEXT_PUBLIC_BUILD_TIME",
  ],
  "src/lib/player-details-client.ts": [
    "fetchPlayerDetails",
    "resetPlayerDetailsCache",
    "attempt < 2",
    "playerDetailsHref",
    "normalizePlayerDetailsPayload",
    'credentials: "omit"',
  ],
  "src/app/layout.tsx": [
    "keywords",
    "robots",
    "category",
    "siteDefaultTitle",
    "siteDefaultDescription",
    "PROJECTION_SEASON",
  ],
  "src/lib/site-meta.ts": [
    "siteDefaultTitle",
    "siteDefaultDescription",
    "siteManifestDescription",
    "PROJECTION_SEASON",
  ],
  "src/app/manifest.ts": [
    "siteManifestDescription",
    "standalone",
    "SITE_BRAND",
    "SITE_SHORT_NAME",
    "categories",
  ],
  "src/lib/rankings-board.ts": [
    "filterAndSortBoard",
    "hideDepthGoalies",
    "coerceSortKeyForPosition",
    "pruneStatRangesForPosition",
    "isStarterEligibleGoalie",
  ],
  "src/lib/goalie-depth.ts": [
    "GOALIE_DEPTH_MAX_GP",
    "isStarterEligibleGoalie",
    "topByPositionLeaders",
  ],
  "src/lib/top-lists.ts": ["steadiestSkaters", "topEdgeSkaters"],
  "src/components/Header.tsx": [
    "headerHeroTitle",
    "headerLeadCopy",
    "headerJumpCtaCopy",
    "headerEyebrowCopy",
    "skipToRankingsCopy",
    "dateTime",
    "scrollToRankings",
    "focusSearch: true",
    "isProjectionStale",
    "HeaderStaleBanner",
    "HeaderRosterNote",
    'aria-keyshortcuts="End"',
  ],
  "src/lib/header-copy.ts": [
    "headerEyebrowCopy",
    "headerHeroTitle",
    "headerLeadCopy",
    "headerJumpCtaCopy",
    "skipToRankingsCopy",
    "SITE_BRAND",
  ],
  "src/components/HeaderRosterNote.tsx": [
    "headerRosterCopy",
    "headerRosterNoteLabel",
    'role="note"',
  ],
  "src/lib/header-roster-copy.ts": [
    "headerRosterCopy",
    "headerRosterNoteLabel",
    "DEFAULT_LEAGUE",
    "Skater cats",
    "Goalie cats",
  ],
  "src/components/HeaderStaleBanner.tsx": [
    "npm run generate",
    "refresh urgently",
    "aria-live",
    "aria-label",
    "staleBannerMessage",
    "staleBannerRole",
    "veryStale",
  ],
  "src/lib/stale-banner.ts": [
    "staleBannerMessage",
    "staleBannerRole",
  ],
  "src/components/SortIcon.tsx": [
    "ArrowUpDown",
    'aria-hidden="true"',
  ],
  "src/components/SortHeader.tsx": [
    "sortHeaderAriaSort",
    "sortHeaderAriaLabel",
    "sortHeaderResetTitle",
    "aria-sort",
  ],
  "src/lib/sort-header.ts": [
    "sortHeaderAriaSort",
    "sortHeaderAriaLabel",
    "sortHeaderResetTitle",
  ],
  "src/lib/position-badge.ts": [
    "positionBadgeTitle",
    "positionBadgeAriaLabel",
    "uniquePositions",
  ],
  "src/components/PositionBadge.tsx": [
    "positionBadgeTitle",
    "positionBadgeAriaLabel",
    "uniquePositions",
    "POSITION_COLORS",
  ],
  "src/lib/board-remaining.ts": [
    "remainingBoardRows",
    "loadMoreLabel",
    "loadMoreAriaLabel",
  ],
  "src/lib/clipboard.ts": ["copyText", "execCommand"],
  "src/lib/projection-age.ts": [
    "projectionAgeDays",
    "isProjectionVeryStale",
  ],
  "src/components/BrandEyebrow.tsx": [
    "SITE_BRAND",
    "tracking-[0.2em]",
  ],
  "src/app/error.tsx": [
    "errorTryAgainCopy",
    "errorBackToRankingsCopy",
    "errorBoundaryTitle",
    "errorBoundaryBody",
    "homeRankingsHref",
    "error.digest",
    "BrandEyebrow",
  ],
  "src/app/global-error.tsx": [
    "errorTryAgainCopy",
    "errorBackToRankingsCopy",
    "globalErrorTitle",
    "globalErrorBody",
    "homeRankingsHref",
    "BrandEyebrow",
    "focus-visible:ring-2",
  ],
  "src/app/loading.tsx": [
    "loadingRankingsCopy",
    'role="status"',
    "BrandEyebrow",
  ],
  "src/lib/app-shell-copy.ts": [
    "loadingRankingsCopy",
    "errorBoundaryTitle",
    "errorBoundaryBody",
    "notFoundTitle",
    "notFoundBody",
    "globalErrorTitle",
    "globalErrorBody",
  ],
  "src/lib/publish-players.ts": ["perStatSigma", "compactBoardNumbers"],
  "src/lib/vor.ts": ["softCapCategoryZ", "PERIPHERAL"],
  "src/lib/format.ts": ["sigmaColor", "edgeColor", "formatSigned"],
  "src/components/TopPlayers.tsx": [
    "TopLeadersCard",
    "HowVorWorks",
    "topByPositionLeaders",
    "playerBoardHref",
    "gamesPlayed}gp",
    "TOP_LEADERS_COPY",
    "topLeadersSectionLabel",
    "steadiestBoardHref",
    "edgeBoardHref",
    "vorForFilter",
    "TopPlayerLink",
    "dense",
    "tabular-nums",
  ],
  "src/lib/top-leaders-copy.ts": [
    "topLeadersSectionLabel",
    "TOP_LEADERS_COPY",
    "Steadiest",
  ],
  "src/components/HowVorWorks.tsx": [
    "How VOR Works",
    "howVorZScoreCopy",
    "howVorReplacementCopy",
    "howVorYahooPositionsCopy",
    "howVorScarcityHintCopy",
    "CATEGORY_FULL_LABELS",
    "Category scarcity weights",
  ],
  "src/lib/how-vor-copy.ts": [
    "howVorZScoreCopy",
    "howVorReplacementCopy",
    "howVorYahooPositionsCopy",
    "howVorScarcityHintCopy",
    "replacementRank",
  ],
  "src/components/TopLeadersCard.tsx": [
    "TopLeadersCard",
    "accentClass",
    "headerExtra",
  ],
  "src/app/page.tsx": [
    "RankingsTable",
    "TopPlayers",
    "SiteFooter",
    "ScrollToTop",
    "rankingsJsonLd",
  ],
  "src/components/SiteFooter.tsx": [
    "boardShortcutsFooterChip",
    "footerDraftableCopy",
    "FOOTER_SOURCE_HREF",
    "formatProjectionEngine",
    "Projections generated",
  ],
  "src/lib/site-footer.ts": [
    "footerDraftableCopy",
    "FOOTER_SOURCE_HREF",
  ],
  "src/components/RankingsStatFilters.tsx": [
    "onDone",
    "doneStatFiltersCopy",
    "clearAllStatFiltersCopy",
    "statFiltersPanelTitle",
    'aria-keyshortcuts="Enter"',
    "normalizeRangeInput",
    "statFiltersHintCopy",
    'role="region"',
    "rankings-stat-filters-hint",
    'type="text"',
    "inputMode",
    "tabular-nums",
  ],
  "src/lib/stat-filters-copy.ts": [
    "statFiltersHintCopy",
    "statFiltersPanelTitle",
    "clearAllStatFiltersCopy",
    "doneStatFiltersCopy",
    "statsFilterButtonLabel",
    "boardFiltersRegionLabel",
    "91.5%",
    "0.915",
  ],
};

let failed = 0;

// Catch duplicate object keys in this file (TS may also fail, but CI order varies).
{
  const self = readFileSync(
    join(root, "scripts/check-ui-contracts.ts"),
    "utf8",
  );
  const keyRe = /^\s+"([^"]+\.[^"]+)": \[/gm;
  const seen = new Map<string, number>();
  let m: RegExpExecArray | null;
  while ((m = keyRe.exec(self))) {
    const k = m[1]!;
    seen.set(k, (seen.get(k) ?? 0) + 1);
  }
  for (const [k, n] of seen) {
    if (n > 1) {
      console.error(`FAIL: duplicate ui-contract key ${JSON.stringify(k)} (×${n})`);
      failed++;
    }
  }
}

for (const [rel, needles] of Object.entries(files)) {
  const text = readFileSync(join(root, rel), "utf8");
  for (const n of needles) {
    if (!text.includes(n)) {
      console.error(`FAIL: ${rel} missing ${JSON.stringify(n)}`);
      failed++;
    }
  }
}

if (failed) process.exit(1);
console.log("OK: ui-contracts");
