/**
 * Lightweight UI contract checks (no browser). Fails if critical board hooks vanish.
 * Run: npx tsx scripts/check-ui-contracts.ts
 */
import { readFileSync } from "fs";
import { join } from "path";

const root = process.cwd();
const files: Record<string, string[]> = {
  "src/components/RankingsTable.tsx": [
    "RankingsTableInner",
    "Suspense",
    "loadingRankingsCopy",
    'role="status"',
    'aria-busy="true"',
    'id="rankings"',
    "rankings-heading",
    "VOR rankings",
  ],
  "src/components/RankingsTableInner.tsx": [
    "usePlayerDetails",
    "useRankingsBoardState",
    "useRankingsUrlSync",
    "useRankingsKeyboard",
    "useBoardCopyLinks",
    "useRankingsHashJump",
    "useRankingsHashJump(board.filtered)",
    "RankingsBoardTable",
    "BoardShortcutsHelp",
    'from "./BoardShortcutsHelp"',
    "searchQueryIsClearable",
    "RankingsBoardChrome",
    "RankingsStatusBar",
    "useHorizontalScrollShadow",
    "useBoardStickyChromeHeight",
    "useCoercedExpandFocusRestore",
    "useBoardDocumentTitle",
    "useExpandedRowScroll",
    "visibleBoardPlayers",
    "onCyclePosition",
    "cycleBoardPosition",
    "onCopyPlayerLink",
  ],
  "src/lib/board-visible.ts": ["visibleBoardPlayers", "boardRowTabStopId"],
  "src/hooks/useExpandedRowScroll.ts": [
    "useExpandedRowScroll",
    "scrollExpandedRowIntoView",
    "isBoardSortHeaderFocus",
    "sortKey",
    "sortDir",
    "ResizeObserver",
    "player-panel-",
    "requestAnimationFrame(attach)",
    "focus: false",
    "Intentionally ignores load-more",
    "details panel",
  ],
  "src/components/RankingsBoardTable.tsx": [
    'id="rankings-board-table"',
    "RankingsPlayerRow",
    "RankingsTableHead",
    "RankingsBoardFooter",
    "group/hscroll",
    "overscroll-x-contain",
    "boardRowTabStopId",
    "anchorId",
    "searchPending",
    "aria-busy",
    "aria-rowcount",
    "boardTableAriaRowCount",
  ],
  "src/hooks/useBoardCopyLinks.ts": [
    "useBoardCopyLinks",
    "copyTextWithFlash",
    "rankingsShareUrl",
    "copyBoardLink",
    "copyPlayerLink",
    "boardShareState(null)",
    "cancelBoardFlashRef",
    "cancelPlayerFlashRef",
  ],
  "src/hooks/useRankingsHashJump.ts": [
    "useRankingsHashJump",
    "filteredPlayers",
    "filteredRef",
    "hashchange",
    "scrollToRankings",
    "rankingsHashShouldFocusSearch",
    "focusSearch: true",
    "!rankingsHashShouldFocusSearch",
  ],
  "src/hooks/useTimedFlash.ts": [
    "useTimedFlash",
    "clearTimeout",
    "holdMs",
  ],
  "src/hooks/useCoercedExpandFocusRestore.ts": [
    "useCoercedExpandFocusRestore",
    "player-row-",
    "focusBoardSearch",
    "preventScroll",
  ],
  "src/hooks/useBoardStickyChromeHeight.ts": [
    "useBoardStickyChromeHeight",
    "syncBoardStickyChromeHeight",
    "BOARD_STICKY_CHROME_SELECTOR",
    "BOARD_STICKY_CHROME_HEIGHT_VAR",
    "ResizeObserver",
  ],
  "src/hooks/useBoardDocumentTitle.ts": [
    "useBoardDocumentTitle",
    "boardDocumentTitle",
    "document.title",
    "sortKey",
    "sortDir",
    "siteDefaultTitle",
    "return () =>",
  ],
  "src/lib/board-document-title.ts": [
    "boardDocumentTitle",
    "boardSortTitleToken",
    "SITE_BRAND",
    "siteDefaultTitle",
  ],
  "src/hooks/useRankingsBoardState.ts": [
    "useRankingsBoardState",
    "boardFilterResetToken",
    "coerceExpandedPlayerId",
    "countActiveStatFilters",
    "resetSortToVor",
    "toggleDepthGoalies",
    "hydrateFromUrl",
    "Drop expand when the player leaves",
    "pruneStatRangesForPosition",
    "canToggleDepthGoalies",
  ],
  "src/components/RankingsBoardChrome.tsx": [
    "boardFiltersRegionLabel",
    "max-md:backdrop-blur-none",
    "max-md:bg-slate-950",
    "motion-reduce:backdrop-blur-none",
    "motion-reduce:bg-slate-950",
    "data-board-sticky-chrome",
    "BoardActiveFilters",
    "RankingsToolbar",
    "helpOpen",
    "focusFirstStatFilterInput",
    "onOpenStats",
  ],
  "src/components/RankingsBoardFooter.tsx": [
    "loadMoreLabel",
    "loadMoreAriaLabel",
    "remainingBoardRows",
    "RankingsEmptyState",
    'aria-keyshortcuts="m"',
    "lastVisiblePlayerId",
    "focusPlayerRow",
    "restoreFocusRef",
    "min-h-11",
    "min-w-[2.75rem]",
    "inline-flex",
    "items-center",
  ],
  "src/lib/board-players.ts": ["boardHasPlayerId", "coerceExpandedPlayerId"],
  "src/lib/board-active-filters.ts": [
    "countActiveStatFilters",
    "isInvertedRangeBound",
  ],
  "src/components/RankingsPlayerRow.tsx": [
    "aria-expanded",
    "aria-controls",
    "aria-rowindex",
    "aria-selected",
    "scroll-mt-[var(--board-sticky-chrome-height,0px)]",
    "isExpanded ? `player-panel-${player.id}` : undefined",
    "isTabStop",
    'role="region"',
    "aria-busy",
    "--board-hscroll-client-width",
    "sticky left-0",
    "vorForFilter",
    "ExpandedPlayerPanel",
    "loading:",
    'role="status"',
    'aria-busy="true"',
    "playerPanelLoadingLabel",
    "ExpandedPlayerPanelFallback",
    "isBoardRowToggleKey",
    "boardRowAriaLabel",
    "boardRowDetailsAriaLabel",
    "boardTableAriaRowIndex",
    "edgeCellTitle",
    "sigmaCellTitle",
    "sigmaCellDisplay",
    "tabular-nums",
    "bg-slate-950/95 max-md:bg-slate-950",
  ],
  "src/lib/board-row-a11y.ts": [
    "boardRowAriaLabel",
    "boardRowDetailsAriaLabel",
    "boardTableAriaRowCount",
    "boardTableAriaRowIndex",
    "edgeCellTitle",
    "sigmaCellTitle",
    "sigmaCellDisplay",
  ],
  "src/lib/rankings-filters.ts": [
    "passesRanges",
    "isInvertedRangeBound",
    "Skip inverted min/max",
  ],
  "src/lib/board-reset-token.ts": [
    "boardFilterResetToken",
    "encodeActiveStatRangesToken",
    "isInvertedRangeBound",
    "g1",
  ],
  "src/lib/board-keyboard.ts": [
    "nextExpandedPlayerId",
    "nextExpandedPlayerIdByStep",
    "BOARD_PAGE_JUMP",
    "shouldPrefetchBoardPage",
    "isBoardRowNavTarget",
    "boardHomeEndPlayerId",
    "isBoardRowToggleKey",
    "isBoardTypingTarget",
    "isBoardChromeTarget",
    "shouldIgnoreBoardShortcut",
    "boardKeyboardNavIds",
    "nextBoardEscapeTypingAction",
    "nextBoardEscapeAction",
    "isBoardImeComposing",
  ],
  "src/components/BoardActiveFilters.tsx": [
    "Active board filters",
    "clearBoardFiltersCopy",
    "boardActiveStatChips",
    "boardActiveFiltersVisible",
    "hasStatFilters",
    "All goalies",
    "showingAllGoalies",
    "focusAfterActiveFilterClear",
  ],
  "src/lib/board-active-filter-chips.ts": [
    "boardActiveStatChips",
    "boardActiveFiltersVisible",
    "formatActiveRangeChip",
    "formatRangeChip",
    "isInvertedRangeBound",
  ],
  "src/components/RankingsTableHead.tsx": [
    'column="sigma"',
    "sticky left-10",
    "w-10 min-w-10 max-w-10",
    "sm:w-12 sm:min-w-12 sm:max-w-12",
    "STICKY_NAME_SHADOW",
    "onResetSort",
    'scope="col"',
    "max-md:backdrop-blur-none",
    "max-md:bg-slate-950",
    "bg-slate-950/95 max-md:bg-slate-950",
    "motion-reduce:bg-slate-950",
    "BOARD_STICKY_TOP_CLASS",
    "aria-rowindex={1}",
  ],
  "src/components/RankingsEmptyState.tsx": [
    "emptyBoardStatusCopy",
    "emptyBoardHintCopy",
    "EMPTY_BOARD_ACTION_LABELS",
    "EmptyAction",
    'role="status"',
    'keyshortcuts="Escape"',
    "emptyBoardRecoveryFlags",
    "text-slate-400",
  ],
  "src/components/EmptyAction.tsx": [
    "EmptyAction",
    "aria-keyshortcuts",
    "primary",
    "min-h-11",
    "min-w-[2.75rem]",
    "inline-flex",
    "items-center",
    "justify-center",
  ],
  "src/lib/board-empty-recovery.ts": [
    "emptyBoardRecoveryFlags",
    "emptyBoardStatusCopy",
    "emptyBoardHintCopy",
    "Use the buttons below",
    "Keyboard:",
    "EMPTY_BOARD_ACTION_LABELS",
    "clearBoardFiltersCopy",
    "canShowAllGoalies",
  ],
  "src/components/RankingsStatusBar.tsx": [
    "aria-live",
    "aria-atomic",
    "aria-busy",
    "searchPending",
    "boardShowingSummary",
    "opacity-70",
    "Enter/Space",
    "boardShortcutsStatusCopy",
    "tabular-nums",
  ],
  "src/lib/board-status.ts": [
    "boardShowingSummary",
    "formatCount",
    "searchPending",
    "Updating…",
  ],
  "src/hooks/useRankingsKeyboard.ts": [
    'e.key === "/"',
    "!helpOpenNow",
    "ArrowDown",
    "BOARD_SORT_HOTKEYS",
    "onResetBoard",
    "filteredRef",
    "renderCountRef",
    "focusStatsFilterButton",
    "focusFirstStatFilterInput",
    "filtersOpenNow",
    "onCopyBoardLink",
    "onCopyPlayerLink",
    'e.key === "Home"',
    'e.key === "End"',
    "nextExpandedPlayerId",
    "nextExpandedPlayerIdByStep",
    "BOARD_PAGE_JUMP",
    "shouldPrefetchBoardPage",
    "boardHomeEndPlayerId",
    "isBoardRowNavTarget",
    "boardKeyboardNavIds",
    "nextBoardEscapeAction",
    "hasQuery",
    "shouldIgnoreBoardShortcut",
    "isBoardTypingTarget",
    "focusPlayerRowIfPanelFocused",
    "focusPlayerRow",
    "onToggleDepthGoalies",
    "onLoadMore",
    "onClearSearch",
    "onCyclePosition",
    'e.key === "r"',
    'e.key === "G"',
    "empty-state recovery chrome",
    'e.key === "PageDown"',
    'e.key === "m"',
    'e.key === "p"',
    'e.key === "["',
  ],
  "src/components/BoardShortcutsHelp.tsx": [
    "Board shortcuts",
    "BOARD_SHORTCUT_ROWS",
    "BOARD_SHORTCUTS_DIALOG_ID",
    "createPortal",
    "data-dialog-portal",
    "useDialogFocusTrap",
    "boardShortcutsCloseAriaLabel",
    'aria-keyshortcuts="Escape"',
  ],
  "src/hooks/useDialogFocusTrap.ts": [
    "useDialogFocusTrap",
    "trapDialogTabKey",
    "dialogFocusableElements",
    "useLayoutEffect",
    "previouslyFocused",
    "isConnected",
    "dataset.dialogPortal",
    'setAttribute("inert"',
    "Escape",
  ],
  "src/lib/dialog-focus.ts": [
    "dialogFocusableElements",
    "trapDialogTabKey",
    "pull it back",
  ],
  "src/lib/board-shortcuts.ts": [
    "BOARD_SHORTCUT_ROWS",
    "BOARD_SHORTCUTS_DIALOG_ID",
    "board-shortcuts-dialog",
    "BOARD_SORT_HOTKEYS",
    "boardShortcutsStatusCopy",
    "boardShortcutsFooterChip",
    "boardShortcutsFaqAnswer",
    "Shift+G",
    "Load more rows",
    "Copy expanded player link",
    "Previous / next position tab",
    "PgDn / PgUp",
    "Open stat filters (Esc closes)",
    "First player (or page top)",
  ],
  "src/lib/copy-flash.ts": [
    "copyTextWithFlash",
    "CopyFlash",
    "boardLinkButtonLabel",
    "boardLinkTitle",
    "boardLinkAriaLabel",
    "playerLinkButtonLabel",
    "playerLinkAriaLabel",
    "playerLinkTitle",
  ],
  "src/lib/board-dom.ts": [
    "preventScroll: true",
    "focusBoardSearchWhenReady",
    "requestAnimationFrame(tick)",
    "focusBoardSearchWhenReady({ preventScroll: true })",
    "focusStatsFilterButton",
    "focusFirstStatFilterInput",
    "focusBoardSearch",
    "focusBoardPositionTab",
    "focusAfterActiveFilterClear",
    'aria-keyshortcuts="f"',
    "STICKY_NAME_SHADOW",
    "STICKY_NAME_BASE",
    "withPinnedWindowScroll",
    "scrollPageTop",
    "scrollToRankings",
    "scrollExpandedRowIntoView",
    "isBoardSortHeaderFocus",
    "stickyAwareScrollDelta",
    "unionVerticalBounds",
    "boardStickyTopInset",
    "boardStickyChromeHeight",
    "syncBoardStickyChromeHeight",
    "BOARD_STICKY_CHROME_SELECTOR",
    "BOARD_STICKY_THEAD_SELECTOR",
    "BOARD_STICKY_CHROME_HEIGHT_VAR",
    "BOARD_STICKY_TOP_CLASS",
    "data-board-sticky-chrome",
    "focusPlayerRow",
    "focusPlayerRowIfPanelFocused",
    "prefersReducedMotion",
  ],
  "src/lib/rankings-export.ts": [
    "rankingsToJsonRows",
    "rankingsJsonExport",
    "rankingsCsvString",
    "downloadRankingsCsv",
    "downloadRankingsJson",
    "exportCategoryStat",
    "exportStatRanges",
    "isInvertedRangeBound",
    "RankingsExportContext",
    "RankingsJsonExportFilters",
    "categories:",
    "filters:",
    "stats:",
    "exportButtonLabel",
    "exportButtonTitle",
    "exportGroupAriaLabel",
    "empty?: boolean",
    "No players to export",
    "vorForFilter",
    "vorScope",
  ],
  "src/lib/rankings-csv.ts": [
    "rankingsToCsv",
    "rankingsCsvMetaLine",
    "downloadTextFile",
    "fantasy-hockey-vor",
    "vorScope",
    "csvEscape",
    "revokeObjectURL",
    "\\uFEFF",
  ],
  "src/components/ExpandedPlayerPanel.tsx": [
    "ExpandedPlayerMeta",
    "ExpandedPlayerCategories",
    "ExpandedPlayerNotes",
  ],
  "src/components/ExpandedPlayerNotes.tsx": [
    "aliveRef",
    "playerId",
    "focusPlayerRow",
    "showRetry",
    "playerNotesLoadingLabel",
    "playerNotesUnavailableCopy",
    "playerNotesRetryLabel",
    "sr-only",
    "Join any in-flight expand fetch",
    'role="alert"',
    'aria-busy="true"',
  ],
  "src/lib/player-notes-copy.ts": [
    "playerNotesLoadingLabel",
    "playerPanelLoadingLabel",
    "playerNotesUnavailableCopy",
    "playerNotesRetryLabel",
  ],
  "src/components/ExpandedPlayerCategories.tsx": [
    "categoryZBarWidth",
    "categoryZScoreLabel",
    "categoryZMeterAriaLabel",
    "categoryProjectionPrefix",
    "detailStatSigma",
    'role="meter"',
    "aria-valuetext",
    "tabular-nums",
  ],
  "src/lib/category-z-bar.ts": [
    "categoryZBarWidth",
    "categorySigmaDigits",
    "categoryZMeterValue",
    "categoryZScoreLabel",
    "categoryZMeterAriaLabel",
    "categoryProjectionPrefix",
  ],
  "src/components/ExpandedPlayerMeta.tsx": [
    "playerLinkButtonLabel",
    "playerLinkAriaLabel",
    "playerLinkTitle",
    'aria-keyshortcuts="p"',
    'aria-live="polite"',
    "projectionMethodLabel",
  ],
  "src/lib/expanded-meta-copy.ts": [
    "confidenceChipCopy",
    "marketEdgeChipCopy",
    "uncertaintyChipCopy",
    "uncertaintyChipTitle",
  ],
  "src/lib/projection-method.ts": [
    "projectionMethodLabel",
    "projectionMethodTone",
  ],
  "src/components/RankingsToolbar.tsx": [
    "RankingsExportButtons",
    "RankingsSearchField",
    "RankingsGoalieDepthToggle",
    "RankingsBoardLinkButton",
    "RankingsHelpButton",
    "RankingsStatsFilterButton",
    "PositionFilterTabs",
    "helpOpen",
  ],
  "src/components/RankingsStatsFilterButton.tsx": [
    'aria-controls={filtersOpen ? "rankings-stat-filters" : undefined}',
    'aria-keyshortcuts="f"',
    "aria-expanded",
    "activeFilterCount",
    "statsFilterButtonLabel",
    "focusFirstStatFilterInput",
    "queueMicrotask",
  ],
  "src/components/RankingsBoardLinkButton.tsx": [
    "boardLinkButtonLabel",
    "boardLinkTitle",
    "boardLinkAriaLabel",
    'aria-keyshortcuts="l"',
    'aria-live="polite"',
    "onCopyBoardLink",
  ],
  "src/components/RankingsHelpButton.tsx": [
    "boardHelpTitle",
    "boardHelpAriaLabel",
    'aria-keyshortcuts="Shift+Slash"',
    'aria-haspopup="dialog"',
    "aria-expanded",
    "aria-controls",
    "BOARD_SHORTCUTS_DIALOG_ID",
    "helpOpen",
    "onOpenHelp",
  ],
  "src/lib/board-help-copy.ts": [
    "boardHelpTitle",
    "boardHelpAriaLabel",
    "boardShortcutsCloseAriaLabel",
  ],
  "src/lib/goalie-depth-toggle.ts": [
    "canToggleDepthGoalies",
    "canOfferAllGoalies",
    "goalieDepthToggleLabel",
    "goalieDepthToggleTitle",
  ],
  "src/components/RankingsGoalieDepthToggle.tsx": [
    "goalieDepthToggleLabel",
    "goalieDepthToggleTitle",
    'aria-keyshortcuts="Shift+G"',
    "GOALIE_DEPTH_MAX_GP",
    "aria-pressed",
  ],
  "src/components/RankingsSearchField.tsx": [
    "searchQueryNearCap",
    "searchQueryLengthLabel",
    "searchQueryIsClearable",
    "searchFieldAriaLabel",
    "searchFieldPlaceholder",
    "clearSearchAriaLabel",
    "HIGHLIGHT_QUERY_MAX",
    "rankings-search-limit",
    "autoComplete",
    'aria-keyshortcuts="Slash"',
    "focusBoardSearch",
  ],
  "src/lib/highlight-match.tsx": [
    "HIGHLIGHT_QUERY_MAX",
    "SEARCH_NEAR_CAP_REMAINING",
    "searchQueryNearCap",
    "searchQueryLengthLabel",
    "searchQueryIsClearable",
    "searchFieldAriaLabel",
    "searchFieldPlaceholder",
    "clearSearchAriaLabel",
    "highlightMatch",
  ],
  "src/components/RankingsExportButtons.tsx": [
    "exportButtonLabel",
    "exportButtonTitle",
    "exportGroupAriaLabel",
    "searchPending",
    "empty",
    "aria-label={blocked ? csvTitle : undefined}",
    "aria-label={blocked ? jsonTitle : undefined}",
    "useTimedFlash",
    "downloadRankingsCsv",
    "downloadRankingsJson",
  ],
  "src/hooks/useBoardInfiniteScroll.ts": [
    "useBoardInfiniteScroll",
    "BOARD_PAGE_SIZE",
    "IntersectionObserver",
    "loadMore",
    "nextVisibleCount",
    "expandVisibleFloor",
    "resolveVisibleCount",
    "applyLoadMoreVisibleCount",
    "skipIoRef",
    "resetGenRef",
    "tokenMountedRef",
    "requestAnimationFrame",
    "collapsing a deep row does not yank",
  ],
  "src/hooks/useHorizontalScrollShadow.ts": [
    "useHorizontalScrollShadow",
    "applyHorizontalScrollChrome",
    "useLayoutEffect",
    "requestAnimationFrame",
    "cancelAnimationFrame",
  ],
  "src/lib/horizontal-scroll-shadow.ts": [
    "HORIZONTAL_SCROLL_SHADOW_PX",
    "HORIZONTAL_SCROLL_SCROLLED_ATTR",
    "BOARD_HSCROLL_CLIENT_WIDTH_VAR",
    "horizontalScrollShadowVisible",
    "applyHorizontalScrollShadow",
    "applyBoardHscrollClientWidth",
    "applyHorizontalScrollChrome",
  ],
  "src/hooks/useRankingsUrlSync.ts": [
    "History.prototype.replaceState",
    "rankingsUrlSyncHref",
    "parseLiveRankingsUrl",
    "window.location.search",
    "rankingsUrlSearch",
    "nextRankingsUrlSyncAction",
    "popstate",
    "onHydrate",
    "query,",
  ],
  "src/hooks/usePlayerDetails.ts": [
    "scheduleIdle",
    "prefersSaveData",
    "fetchPlayerDetails",
    "expandedId == null || details != null",
    "Stay silent on idle failure",
    "expandRequestIdRef",
    "requestId",
  ],
  "src/lib/schedule-idle.ts": [
    "scheduleIdle",
    "prefersSaveData",
    "requestIdleCallback",
    "cancelIdleCallback",
  ],
  "src/components/PositionFilterTabs.tsx": [
    'role="tablist"',
    "ArrowRight",
    "positionFilterTablistLabel",
    "BOARD_POSITIONS",
    "nextBoardPositionIndex",
    "aria-controls",
    "rankings-board-table",
    'aria-keyshortcuts="[ ]"',
    "aria-live",
    "positionFilterAnnounce",
    "boardPositionTabId",
  ],
  "src/lib/board-positions.ts": [
    "BOARD_POSITIONS",
    "nextBoardPositionIndex",
    "cycleBoardPosition",
    "boardPositionTabId",
    "positionFilterAnnounce",
    "positionFilterTablistLabel",
  ],
  "src/lib/rankings-url.ts": [
    "hideDepthGoalies",
    "playerId",
    "encodeStatRanges",
    "decodeStatRanges",
    "splitStatRangeBounds",
    "parsePlayerIdParam",
    "/^[1-9]\\d{0,15}$/",
    "Number.isSafeInteger",
    "isInvertedRangeBound",
    'toLowerCase() !== "all"',
    "params.get(\"dir\")?.toLowerCase()",
    "k.toLowerCase() === keyRaw.toLowerCase()",
    "rf",
    "steadiestBoardHref",
    "playerBoardHref",
    "rf=${rf}",
    "HIGHLIGHT_QUERY_MAX",
    "RANGE_BOUND_MAX",
    "nextRankingsUrlSyncAction",
    "parseLiveRankingsUrl",
    "rankingsHashShouldFocusSearch",
    "boardHasPlayerId",
    "rankingsUrlSyncHref",
    "pruneStatRangesForPosition",
  ],
  "src/components/ScrollToTop.tsx": [
    "scrollToTopAriaLabel",
    "scrollToTopTitle",
    "requestAnimationFrame",
    "scrollPageTop",
    "focusBoardSearch",
    "scrollToTopShouldRestoreFocus",
    "buttonRef",
    "pointer-events-none",
    "scrollToTopVisible",
    "motion-reduce:transition-none",
    "motion-reduce:backdrop-blur-none",
  ],
  "src/lib/scroll-to-top.ts": [
    "scrollToTopVisible",
    "scrollToTopShouldRestoreFocus",
    "scrollToTopAriaLabel",
    "scrollToTopTitle",
    "SCROLL_TOP_SHOW_AFTER",
    "SCROLL_TOP_HIDE_BELOW",
  ],
  "src/components/TopPlayerLink.tsx": [
    "TopPlayerLink",
    "dense",
    "hover:bg-white/[0.07]",
    "motion-reduce:transition-none",
  ],
  "src/app/not-found.tsx": [
    "notFoundTitle",
    "notFoundBody",
    "errorBackToRankingsCopy",
    "homeRankingsHref",
    "BrandEyebrow",
    "export const metadata",
    "index: false",
    "robots",
  ],
  "src/lib/seo-jsonld.ts": [
    "WebApplication",
    "Dataset",
    "FAQPage",
    "BreadcrumbList",
    "HowTo",
    "isAccessibleForFree",
    "keywords",
    "National Hockey League",
    "sameAs",
    "boardShortcutsFaqAnswer",
    "SITE_BRAND",
    "serializeJsonLd",
    "replace(/</g",
    "\\u003c",
  ],
  "src/lib/site.ts": [
    "SITE_ORIGIN",
    "SITE_URL",
    "SITE_BRAND",
    "SITE_SHORT_NAME",
    "homeRankingsHref",
    "playerDetailsHref",
    "NEXT_PUBLIC_BUILD_TIME",
  ],
  "src/lib/player-details-client.ts": [
    "fetchPlayerDetails",
    "resetPlayerDetailsCache",
    "attempt < 2",
    "playerDetailsHref",
    "normalizePlayerDetailsPayload",
    'credentials: "omit"',
  ],
  "src/app/layout.tsx": [
    "keywords",
    "robots",
    "category",
    "siteDefaultTitle",
    "siteDefaultDescription",
    "description: defaultDescription",
    "PROJECTION_SEASON",
    "summary_large_image",
    "appleWebApp",
    "black-translucent",
    "capable: true",
    "SITE_SHORT_NAME",
  ],
  "src/app/opengraph-image.tsx": [
    "ImageResponse",
    "force-static",
    "SITE_BRAND",
    "PROJECTION_SEASON",
    "1200",
    "630",
  ],
  "src/app/twitter-image.tsx": [
    "OpenGraphImage",
    "force-static",
    "TwitterImage",
  ],
  "src/lib/site-meta.ts": [
    "siteDefaultTitle",
    "siteDefaultDescription",
    "siteManifestDescription",
    "PROJECTION_SEASON",
  ],
  "src/app/manifest.ts": [
    "siteManifestDescription",
    "standalone",
    "SITE_BRAND",
    "SITE_SHORT_NAME",
    "categories",
  ],
  "src/lib/rankings-board.ts": [
    "filterAndSortBoard",
    "hideDepthGoalies",
    "coerceSortKeyForPosition",
    "pruneStatRangesForPosition",
    "isStarterEligibleGoalie",
  ],
  "src/lib/goalie-depth.ts": [
    "GOALIE_DEPTH_MAX_GP",
    "isStarterEligibleGoalie",
    "topByPositionLeaders",
  ],
  "src/lib/top-lists.ts": ["steadiestSkaters", "topEdgeSkaters"],
  "src/components/Header.tsx": [
    "headerHeroTitle",
    "headerLeadCopy",
    "headerJumpCtaCopy",
    "headerEyebrowCopy",
    "skipToRankingsCopy",
    "dateTime",
    "scrollToRankings",
    "focusSearch: true",
    "useLiveProjectionAge",
    "isProjectionStale",
    "HeaderStaleBanner",
    "HeaderRosterNote",
    "Jump to board + focus search",
    "safe-area-inset-top",
  ],
  "src/hooks/useLiveProjectionAge.ts": [
    "useLiveProjectionAge",
    "projectionAgeDays",
    "visibilitychange",
    "new Date().toISOString()",
  ],
  "src/lib/header-copy.ts": [
    "headerEyebrowCopy",
    "headerHeroTitle",
    "headerLeadCopy",
    "headerJumpCtaCopy",
    "skipToRankingsCopy",
    "SITE_BRAND",
  ],
  "src/components/HeaderRosterNote.tsx": [
    "headerRosterCopy",
    "headerRosterNoteLabel",
    'role="note"',
  ],
  "src/lib/header-roster-copy.ts": [
    "headerRosterCopy",
    "headerRosterNoteLabel",
    "DEFAULT_LEAGUE",
    "Skater cats",
    "Goalie cats",
  ],
  "src/components/HeaderStaleBanner.tsx": [
    "npm run generate",
    "refresh urgently",
    "aria-live",
    "aria-label",
    "staleBannerMessage",
    "staleBannerRole",
    "veryStale",
  ],
  "src/lib/stale-banner.ts": [
    "staleBannerMessage",
    "staleBannerRole",
  ],
  "src/components/SortIcon.tsx": [
    "ArrowUpDown",
    "compact",
    'aria-hidden="true"',
  ],
  "src/components/SortHeader.tsx": [
    "sortHeaderAriaSort",
    "sortHeaderAriaLabel",
    "sortHeaderResetTitle",
    "aria-sort",
    "compact",
  ],

  "src/lib/sort-header.ts": [
    "sortHeaderAriaSort",
    "sortHeaderAriaLabel",
    "sortHeaderResetTitle",
  ],
  "src/lib/position-badge.ts": [
    "positionBadgeTitle",
    "positionBadgeAriaLabel",
    "uniquePositions",
  ],
  "src/components/PositionBadge.tsx": [
    "positionBadgeTitle",
    "positionBadgeAriaLabel",
    "uniquePositions",
    "POSITION_COLORS",
  ],
  "src/lib/board-remaining.ts": [
    "remainingBoardRows",
    "loadMoreLabel",
    "loadMoreAriaLabel",
  ],
  "src/lib/clipboard.ts": ["copyText", "execCommand"],
  "src/lib/projection-age.ts": [
    "projectionAgeDays",
    "isProjectionVeryStale",
    "sitemapLastModified",
  ],
  "src/app/sitemap.ts": [
    "sitemapLastModified",
    "sitemapChangeFrequency",
    "projectionAgeDays",
    "getProjections",
    "SITE_URL",
    "force-static",
    "lastModified",
  ],
  "src/components/BrandEyebrow.tsx": [
    "SITE_BRAND",
    "tracking-[0.2em]",
  ],
  "src/app/robots.ts": [
    "SITE_ORIGIN",
    "sitemap.xml",
    "NEXT_PUBLIC_BASE_PATH",
    'userAgent: "*"',
    "force-static",
    'basePath ? `${basePath}/` : "/"',
  ],
  "src/app/error.tsx": [
    "errorTryAgainCopy",
    "errorBackToRankingsCopy",
    "errorBoundaryTitle",
    "errorBoundaryBody",
    "homeRankingsHref",
    "error.digest",
    "BrandEyebrow",
    "focus-visible:outline-none",
    "focus-visible:ring-2",
  ],
  "src/app/global-error.tsx": [
    "errorTryAgainCopy",
    "errorBackToRankingsCopy",
    "globalErrorTitle",
    "globalErrorBody",
    "homeRankingsHref",
    "BrandEyebrow",
    "focus-visible:ring-2",
    "globals.css",
    "--font-geist-sans",
    "console.error",
    "error.digest",
    "useEffect",
  ],
  "src/app/loading.tsx": [
    "loadingRankingsCopy",
    'role="status"',
    'aria-busy="true"',
    "BrandEyebrow",
  ],
  "src/lib/app-shell-copy.ts": [
    "loadingRankingsCopy",
    "errorBoundaryTitle",
    "errorBoundaryBody",
    "notFoundTitle",
    "notFoundBody",
    "globalErrorTitle",
    "globalErrorBody",
  ],
  "src/lib/publish-players.ts": ["perStatSigma", "compactBoardNumbers"],
  "src/lib/vor.ts": ["softCapCategoryZ", "PERIPHERAL"],
  "src/lib/format.ts": ["sigmaColor", "edgeColor", "formatSigned"],
  "src/components/TopPlayers.tsx": [
    "TopLeadersCard",
    "HowVorWorks",
    "topByPositionLeaders",
    "playerBoardHref",
    "gamesPlayed}gp",
    "TOP_LEADERS_COPY",
    "topLeadersSectionLabel",
    "steadiestBoardHref",
    "edgeBoardHref",
    "vorForFilter",
    "TopPlayerLink",
    "dense",
    "tabular-nums",
  ],
  "src/lib/top-leaders-copy.ts": [
    "topLeadersSectionLabel",
    "TOP_LEADERS_COPY",
    "Steadiest",
  ],
  "src/components/HowVorWorks.tsx": [
    "How VOR Works",
    "how-vor-works-title",
    "aria-labelledby",
    "content-visibility:auto",
    "contain-intrinsic-size",
    "howVorZScoreCopy",
    "howVorReplacementCopy",
    "howVorYahooPositionsCopy",
    "howVorScarcityHintCopy",
    "howVorScarcityTitleCopy",
    "howVorScarcitySkatersLabel",
    "howVorScarcityGoaliesLabel",
    "CATEGORY_FULL_LABELS",
  ],
  "src/lib/how-vor-copy.ts": [
    "howVorZScoreCopy",
    "howVorReplacementCopy",
    "howVorYahooPositionsCopy",
    "howVorScarcityHintCopy",
    "howVorScarcityTitleCopy",
    "howVorScarcitySkatersLabel",
    "howVorScarcityGoaliesLabel",
    "Category scarcity weights",
    "replacementRank",
  ],
  "src/components/TopLeadersCard.tsx": [
    "TopLeadersCard",
    "accentClass",
    "headerExtra",
    "aria-labelledby",
    "top-leaders-",
  ],
  "src/app/page.tsx": [
    "RankingsTable",
    "TopPlayers",
    "SiteFooter",
    "ScrollToTop",
    "rankingsJsonLd",
    "serializeJsonLd",
    "safe-area-inset-bottom",
  ],
  "src/components/SiteFooter.tsx": [
    "boardShortcutsFooterChip",
    "footerDraftableCopy",
    "FOOTER_SOURCE_HREF",
    "formatProjectionEngine",
    "Projections generated",
    "safe-area-inset-bottom",
  ],
  "src/lib/site-footer.ts": [
    "footerDraftableCopy",
    "FOOTER_SOURCE_HREF",
  ],
  "src/components/RankingsStatFilters.tsx": [
    "onDone",
    "doneStatFiltersCopy",
    "clearAllStatFiltersCopy",
    "statFiltersPanelTitle",
    'aria-keyshortcuts="Enter"',
    "normalizeRangeInput",
    "isInvertedRangeBound",
    "aria-invalid",
    "Min is greater than max",
    "statFiltersHintCopy",
    "text-slate-400",
    'role="region"',
    "rankings-stat-filters-hint",
    'type="text"',
    "inputMode",
    "tabular-nums",
    "min-h-11",
    "min-w-[2.75rem]",
    "inline-flex",
    "items-center",
    "focusFirstStatFilterInput",
    "queueMicrotask",
  ],
  "src/lib/stat-filters-copy.ts": [
    "statFiltersHintCopy",
    "statFiltersPanelTitle",
    "clearAllStatFiltersCopy",
    "doneStatFiltersCopy",
    "statsFilterButtonLabel",
    "boardFiltersRegionLabel",
    "91.5%",
    "0.915",
  ],
};

let failed = 0;

// Catch duplicate object keys in this file (TS may also fail, but CI order varies).
{
  const self = readFileSync(
    join(root, "scripts/check-ui-contracts.ts"),
    "utf8",
  );
  const keyRe = /^\s+"([^"]+\.[^"]+)": \[/gm;
  const seen = new Map<string, number>();
  let m: RegExpExecArray | null;
  while ((m = keyRe.exec(self))) {
    const k = m[1]!;
    seen.set(k, (seen.get(k) ?? 0) + 1);
  }
  for (const [k, n] of seen) {
    if (n > 1) {
      console.error(`FAIL: duplicate ui-contract key ${JSON.stringify(k)} (×${n})`);
      failed++;
    }
  }
}

for (const [rel, needles] of Object.entries(files)) {
  const text = readFileSync(join(root, rel), "utf8");
  for (const n of needles) {
    if (!text.includes(n)) {
      console.error(`FAIL: ${rel} missing ${JSON.stringify(n)}`);
      failed++;
    }
  }
}

if (failed) process.exit(1);
console.log("OK: ui-contracts");
