/**
 * Parity of the committed pre-season board with the model: ten reference
 * skaters re-projected now (committed bundle + the dataset it was trained
 * on) must find their published model GP and per-game rates again, ±1 game
 * and ±1 per 82 games. The 2026-07-30 board failed this by 10+ games and
 * +46 % goals per 82 (a dataset that no longer matched the bundle).
 *
 * src/data/ml/dataset.json is gitignored: without it (or with another
 * dataset than the bundle's) the test says so and skips.
 * Run: npx tsx scripts/test-v2-parity.ts
 */
import { existsSync, readFileSync } from "fs";
import { join } from "path";
import { datasetMismatch, readDatasetManifest } from "../src/lib/ml/dataset-manifest";
import { getV2Runtime, projectSkaterV2 } from "../src/lib/ml/predict-v2";
import { buildTeamDepthFromProfiles, setInferenceTeamDepthCache } from "../src/lib/ml/team-depth";
import { normalizeProfile } from "../src/lib/player-profile";
import type { PlayerProfile } from "../src/lib/profile-types";
import { applyYahooPositionsToPlayer, loadYahooPositions } from "../src/lib/yahoo-positions";

const REFERENCE = [
  "Connor McDavid",
  "Nathan MacKinnon",
  "Macklin Celebrini",
  "Cale Makar",
  "Mitch Marner",
  "Rasmus Andersson",
  "Cole Caufield",
  "Moritz Seider",
  "Brandon Duhaime",
  "Auston Matthews",
];
const STATS = ["goals", "assists", "shots", "hits", "blocks", "powerplayPoints", "penaltyMinutes", "faceoffWins"];

const root = process.cwd();
const manifest = readDatasetManifest();
if (!manifest) {
  console.log("SKIP: v2 parity — src/data/ml/dataset.json absent (gitignored; npm run ml:dataset)");
  process.exit(0);
}
const rt = getV2Runtime();
if (!rt) {
  console.error("FAIL: v2 runtime unavailable with a dataset present");
  process.exit(1);
}
const mismatch = datasetMismatch(rt.bundle, manifest);
if (mismatch) {
  console.log(`SKIP: v2 parity — ${mismatch}`);
  process.exit(0);
}

const board = JSON.parse(readFileSync(join(root, "src", "data", "players-preseason.json"), "utf8")) as {
  players: Array<{ id: number; name: string; modelGamesPlayed?: number; gamesPlayed: number }>;
};
const detailsPath = join(root, "public", "player-details.json");
const details = existsSync(detailsPath)
  ? (JSON.parse(readFileSync(detailsPath, "utf8")) as Record<string, { modelRates?: Record<string, number> }>)
  : {};
const yahoo = loadYahooPositions();
const profiles = (JSON.parse(readFileSync(join(root, "src", "data", "player-profiles.json"), "utf8")) as { profiles: PlayerProfile[] }).profiles
  .map(normalizeProfile)
  .map((p) => {
    const { positionSource: _s, ...rest } = applyYahooPositionsToPlayer(p, yahoo);
    return rest as PlayerProfile;
  });
setInferenceTeamDepthCache(buildTeamDepthFromProfiles(profiles));

let failed = 0;
let checked = 0;
for (const name of REFERENCE) {
  const profile = profiles.find((p) => p.name === name);
  const published = board.players.find((p) => p.name === name);
  if (!profile || !published) {
    console.error(`FAIL: reference ${name} missing from the profiles or the board`);
    failed++;
    continue;
  }
  const v2 = projectSkaterV2(profile);
  if (!v2) {
    console.error(`FAIL: ${name}: no v2 projection`);
    failed++;
    continue;
  }
  checked++;
  const model = published.modelGamesPlayed ?? published.gamesPlayed;
  if (Math.abs(v2.gamesPlayed - model) > 1) {
    console.error(`FAIL: ${name}: model GP ${v2.gamesPlayed} now, ${model} published`);
    failed++;
  }
  const rates = details[String(published.id)]?.modelRates;
  if (!rates) {
    console.error(`FAIL: ${name}: no published modelRates`);
    failed++;
    continue;
  }
  for (const s of STATS) {
    const now = (v2.perGame[s] ?? 0) * 82;
    const then = (rates[s] ?? 0) * 82;
    if (Math.abs(now - then) > 1) {
      console.error(`FAIL: ${name}: ${s} ${now.toFixed(1)} per 82 now, ${then.toFixed(1)} published`);
      failed++;
    }
  }
}
if (failed > 0) {
  console.error(`${failed} parity failure(s): the board was not generated by this bundle and dataset (npm run generate)`);
  process.exit(1);
}
console.log(`OK: v2 parity — ${checked} reference skaters match the published board (dataset ${manifest.sha1.slice(0, 12)})`);
