import type { SkaterMlTarget } from "./types";

/**
 * Curated auxiliary lag stats per target — avoids feeding 56 irrelevant/noisy
 * features into every ridge model (major overfitting source with λ=1.5).
 */
export const TARGET_AUX_LAG_STATS: Record<SkaterMlTarget, readonly string[]> = {
  goals: [
    "toiPerGame",
    "evToiPerGame",
    "satFor60",
    "shotsFor60",
    "xGoals",
    "xGoalsPer60",
    "goalsAboveExpected",
    "flurryAdjustedxGoals",
    "shootingPct",
    "shootingPct5v5",
    "onIceShootingPct",
    "highDangerxGoals",
    "highDangerGoals",
    "ppGoalsPer60",
    "evGoals",
    "points",
    "satRelative",
    "gameScore",
  ],
  assists: [
    "toiPerGame",
    "evToiPerGame",
    "satFor60",
    "evPoints",
    "points",
    "takeaways",
    "takeawaysPer60",
    "onIceXGoalsPct",
    "satRelative",
    "usatRelative",
    "ppPointsPer60",
    "ppToiPerGame",
    "gameScore",
    "xGoalsPer60",
    "evenStrengthGoalDiff",
    "plusMinus",
  ],
  shots: [
    "toiPerGame",
    "evToiPerGame",
    "satFor60",
    "shotsFor60",
    "totalShotAttempts",
    "missedShots",
    "xGoalsPer60",
    "ppShotsPer60",
    "satPct",
    "usatPct",
    "onIceShootingPct",
    "highDangerShots",
    "ppToiPerGame",
    "goalsAboveExpected",
  ],
  blocks: [
    "blockedShotsPer60",
    "hitsPer60",
    "dZoneStartPct",
    "zoneStartPct5v5",
    "hits",
    "giveaways",
    "toiPerGame",
    "shiftsPerGame",
    "evenStrengthGoalDiff",
    "satRelative",
  ],
  hits: [
    "hitsPer60",
    "hits",
    "takeaways",
    "blockedShotsPer60",
    "toiPerGame",
    "giveawaysPer60",
    "satFor60",
    "shiftsPerGame",
  ],
  powerplayPoints: [
    "ppToiPerGame",
    "ppToiPctPerGame",
    "ppGoalsPer60",
    "ppPointsPer60",
    "ppShotsPer60",
    "ppGoals",
    "ppGoalsFor",
    "evGoals",
    "shootingPct",
    "xGoals",
    "onIceXGoalsPct",
  ],
  penaltyMinutes: [
    "penaltiesDrawn",
    "penaltiesDrawnPer60",
    "giveaways",
    "giveawaysPer60",
    "hitsPer60",
    "takeawaysPer60",
  ],
  faceoffWins: [
    "totalFaceoffs",
    "faceoffWinPct",
    "evToiPerGame",
    "toiPerGame",
    "points",
    "oZoneStartPct",
  ],
};

export function targetAuxStats(target: SkaterMlTarget): readonly string[] {
  return TARGET_AUX_LAG_STATS[target];
}
